/**
 * Stub module for WASM bindings — used when WASM is not built.
 * The actual module is generated by wasm-pack and replaces this file.
 * All methods mirror the Rust AxiaEngine API.
 */
export class AxiaEngine {
  __wbg_ptr = 0;
  free(): void {}
  draw_line(_x1: number, _y1: number, _z1: number, _x2: number, _y2: number, _z2: number, _nx: number, _ny: number, _nz: number): number { return 0; }
  draw_rect(_x: number, _y: number, _z: number, _nx: number, _ny: number, _nz: number, _ux: number, _uy: number, _uz: number, _w: number, _h: number): number { return 0; }
  draw_circle(_cx: number, _cy: number, _cz: number, _nx: number, _ny: number, _nz: number, _r: number, _seg: number): number { return 0; }
  push_pull(_faceId: number, _dist: number): boolean { return false; }
  undo(): boolean { return false; }
  redo(): boolean { return false; }
  get_positions(): Float32Array { return new Float32Array(); }
  get_normals(): Float32Array { return new Float32Array(); }
  get_indices(): Uint32Array { return new Uint32Array(); }
  get_face_map(): Uint32Array { return new Uint32Array(); }
  get_face_normal(_faceId: number): Float64Array { return new Float64Array(3); }
  delete_face(_faceId: number): boolean { return false; }
  face_count(): number { return 0; }
  get_stats(): string { return '{}'; }
  orient_faces(): number { return 0; }
  vert_count(): number { return 0; }
  can_undo(): boolean { return false; }
  can_redo(): boolean { return false; }
}

export default async function init(): Promise<void> {}
